# Generated by Django 4.0 on 2022-02-05 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_topics'),
        ('farts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fart',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/%Y-%m-%d/%H-%M-%S'),
        ),
        migrations.AddField(
            model_name='fart',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y-%m-%d/%H-%M-%S'),
        ),
        migrations.AddField(
            model_name='fart',
            name='link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='fart',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fart',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tags.topics'),
        ),
        migrations.AlterField(
            model_name='fart',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
