# Generated by Django 4.0 on 2022-02-06 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_topics'),
        ('farts', '0002_fart_audio_fart_image_fart_link_fart_text_fart_topic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fart',
            name='title',
        ),
        migrations.AlterField(
            model_name='fart',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tags.categories'),
        ),
        migrations.AlterField(
            model_name='fart',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='fart',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tags.topics'),
        ),
        migrations.AlterField(
            model_name='fart',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tags.types'),
        ),
    ]
