# Generated by Django 4.0 on 2022-04-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farts', '0003_remove_fart_title_alter_fart_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fart',
            name='type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('AUDIO', 'Audio'), ('IMAGE', 'Image'), ('LINK', 'Link')], default='TEXT', max_length=5),
        ),
    ]
