# Generated by Django 4.0 on 2022-04-24 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_topics'),
        ('farts', '0004_alter_fart_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fart',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='fart',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tags.projects'),
        ),
    ]
