# Generated by Django 4.0 on 2022-05-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farts', '0005_fart_title_alter_fart_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='fart',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fart',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
