# Generated by Django 4.0 on 2022-05-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farts', '0006_fart_date_alter_fart_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fart',
            name='type',
            field=models.CharField(choices=[('LINK', 'Link'), ('IMAGE', 'Image'), ('AUDIO', 'Audio'), ('TEXT', 'Text')], default='TEXT', max_length=5),
        ),
    ]
